//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources___Copia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources___Copia() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoFinal.Resources.StringResources - Copia", typeof(StringResources___Copia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de lugar.
        /// </summary>
        internal static string btn1 {
            get {
                return ResourceManager.GetString("btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string btn10 {
            get {
                return ResourceManager.GetString("btn10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja de lugar.
        /// </summary>
        internal static string btn2 {
            get {
                return ResourceManager.GetString("btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de dato.
        /// </summary>
        internal static string btn3 {
            get {
                return ResourceManager.GetString("btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de ruta.
        /// </summary>
        internal static string btn4 {
            get {
                return ResourceManager.GetString("btn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja de ruta.
        /// </summary>
        internal static string btn5 {
            get {
                return ResourceManager.GetString("btn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de dato.
        /// </summary>
        internal static string btn6 {
            get {
                return ResourceManager.GetString("btn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta mas corta.
        /// </summary>
        internal static string btn7 {
            get {
                return ResourceManager.GetString("btn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta alterna.
        /// </summary>
        internal static string btn8 {
            get {
                return ResourceManager.GetString("btn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar de nombre.
        /// </summary>
        internal static string btn9 {
            get {
                return ResourceManager.GetString("btn9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del lugar.
        /// </summary>
        internal static string lbl1 {
            get {
                return ResourceManager.GetString("lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minutos.
        /// </summary>
        internal static string lbl10 {
            get {
                return ResourceManager.GetString("lbl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pesos.
        /// </summary>
        internal static string lbl11 {
            get {
                return ResourceManager.GetString("lbl11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minutos.
        /// </summary>
        internal static string lbl12 {
            get {
                return ResourceManager.GetString("lbl12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pesos.
        /// </summary>
        internal static string lbl13 {
            get {
                return ResourceManager.GetString("lbl13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar donde inicia .
        /// </summary>
        internal static string lbl14 {
            get {
                return ResourceManager.GetString("lbl14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar donde termina.
        /// </summary>
        internal static string lbl15 {
            get {
                return ResourceManager.GetString("lbl15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medio de transporte.
        /// </summary>
        internal static string lbl16 {
            get {
                return ResourceManager.GetString("lbl16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camino.
        /// </summary>
        internal static string lbl17 {
            get {
                return ResourceManager.GetString("lbl17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Totales.
        /// </summary>
        internal static string lbl18 {
            get {
                return ResourceManager.GetString("lbl18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autores.
        /// </summary>
        internal static string lbl19 {
            get {
                return ResourceManager.GetString("lbl19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar donde inicia.
        /// </summary>
        internal static string lbl2 {
            get {
                return ResourceManager.GetString("lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre actual : .
        /// </summary>
        internal static string lbl20 {
            get {
                return ResourceManager.GetString("lbl20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre nuevo :.
        /// </summary>
        internal static string lbl21 {
            get {
                return ResourceManager.GetString("lbl21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar donde termina.
        /// </summary>
        internal static string lbl3 {
            get {
                return ResourceManager.GetString("lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia.
        /// </summary>
        internal static string lbl4 {
            get {
                return ResourceManager.GetString("lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kms.
        /// </summary>
        internal static string lbl5 {
            get {
                return ResourceManager.GetString("lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo si se recorre en auto rentado.
        /// </summary>
        internal static string lbl6 {
            get {
                return ResourceManager.GetString("lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo si se recorren en auto rentado.
        /// </summary>
        internal static string lbl7 {
            get {
                return ResourceManager.GetString("lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo si se recorre en transporte público.
        /// </summary>
        internal static string lbl8 {
            get {
                return ResourceManager.GetString("lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo si se recorre en transporte público.
        /// </summary>
        internal static string lbl9 {
            get {
                return ResourceManager.GetString("lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carro.
        /// </summary>
        internal static string rb1 {
            get {
                return ResourceManager.GetString("rb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte público.
        /// </summary>
        internal static string rb2 {
            get {
                return ResourceManager.GetString("rb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia.
        /// </summary>
        internal static string rb3 {
            get {
                return ResourceManager.GetString("rb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo.
        /// </summary>
        internal static string rb4 {
            get {
                return ResourceManager.GetString("rb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo.
        /// </summary>
        internal static string rb5 {
            get {
                return ResourceManager.GetString("rb5", resourceCulture);
            }
        }
    }
}
